package edu.uclm.esi.videochat;

// Generated by Selenium IDE
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import java.util.*;
import java.util.concurrent.TimeUnit;
import org.junit.Test;
import org.junit.After;
import org.junit.Before;
import org.junit.runner.RunWith;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import edu.uclm.esi.videochat.model.User;
import edu.uclm.esi.videochat.springdao.UserRepository;


@RunWith(SpringJUnit4ClassRunner.class)
@SpringBootTest
public class LoginTest {
	private WebDriver chromeDriver;
	private WebDriver firefoxDriver;

	JavascriptExecutor js;
	
	@Autowired
	UserRepository usersRepo;
	
	@Before
	/* Comun a todos */
	public void setUp() {
		System.setProperty("webdriver.chrome.driver", "C:/Users/raulvj/Downloads/chromedriver.exe");
		System.setProperty("webdriver.gecko.driver", "C:/Users/raulvj/Downloads/geckodriver.exe");
			
		chromeDriver = new ChromeDriver();
		firefoxDriver = new FirefoxDriver();
		
		chromeDriver.manage().timeouts().implicitlyWait(5, TimeUnit.SECONDS);
		
		js = (JavascriptExecutor) chromeDriver;
		
	}
	  
	@After
	/* Comun a cada caso de prueba */
	public void tearDown() {
		chromeDriver.quit();
		firefoxDriver.quit();
	}
	
	@Test
	public void conversacion() {
		hacerLogin(chromeDriver, "johndoe", "j");
		hacerLogin(firefoxDriver, "harley", "q");
		
		try { Thread.sleep(1000); } catch (InterruptedException e ) { }
		
		/* Pepe manda mensaje a Ana */
		chromeDriver.findElement(By.linkText("harley")).click();
		String mensaje = "Hola mi dulce Harley";
		chromeDriver.findElement(By.xpath("/html/body/div/oj-module/div[1]/div[2]/div/div/div/div[1]/div[2]/div/input")).sendKeys(mensaje);
		chromeDriver.findElement(By.xpath("/html/body/div/oj-module/div[1]/div[2]/div/div/div/div[1]/div[2]/div/button[1]")).click();
		
		try { Thread.sleep(1000); } catch (InterruptedException e ) { }
		
		String body = firefoxDriver.findElement(By.tagName("body")).getText();
		assertTrue(body.contains(mensaje));
	}
	  
	private void hacerLogin(WebDriver driver, String nombre, String pwd) {
		driver.get("https://localhost:7500/");
		
		/* Para aceptar el Cerficado de conexión no segura y acceder a localhost */
		if (driver instanceof ChromeDriver) {
			driver.findElement(By.id("details-button")).click();
			driver.findElement(By.id("proceed-link")).click();
		}
		
		//WebElement cajaNombre = chromeDriver.findElement(By.cssSelector(".oj-sm-12:nth-child(1) > input"));
		//WebElement cajaPwd = chromeDriver.findElement(By.cssSelector(".oj-sm-12:nth-child(2) > input"));
		//cajaNombre.clear();
		//cajaPwd.clear();
		driver.findElement(By.cssSelector(".oj-sm-12:nth-child(1) > input")).click();
		driver.findElement(By.cssSelector(".oj-sm-12:nth-child(1) > input")).sendKeys(nombre);
		driver.findElement(By.cssSelector(".oj-sm-12:nth-child(2) > input")).click();
		driver.findElement(By.cssSelector(".oj-sm-12:nth-child(2) > input")).sendKeys(pwd);
		driver.findElement(By.cssSelector("button")).click();		
	}

	@Test
	public void login() {
		chromeDriver.get("https://localhost:7500/");
		
		/* Para aceptar el Cerficado de conexión no segura y acceder a localhost */
		chromeDriver.findElement(By.id("details-button")).click();
		chromeDriver.findElement(By.id("proceed-link")).click();
		
		//WebElement cajaNombre = chromeDriver.findElement(By.cssSelector(".oj-sm-12:nth-child(1) > input"));
		//WebElement cajaPwd = chromeDriver.findElement(By.cssSelector(".oj-sm-12:nth-child(2) > input"));
		//cajaNombre.clear();
		//cajaPwd.clear();
		chromeDriver.findElement(By.cssSelector(".oj-sm-12:nth-child(1) > input")).click();
		chromeDriver.findElement(By.cssSelector(".oj-sm-12:nth-child(1) > input")).sendKeys("johndoe");
		chromeDriver.findElement(By.cssSelector(".oj-sm-12:nth-child(2) > input")).click();
		chromeDriver.findElement(By.cssSelector(".oj-sm-12:nth-child(2) > input")).sendKeys("j");
		chromeDriver.findElement(By.cssSelector("button")).click();
		
		try { Thread.sleep(500); } catch (InterruptedException e ) { }
		
		assertThat(chromeDriver.findElement(By.cssSelector(".oj-hybrid-padding > h1")).getText(), is("Zona de conversación"));
	}
	
	@Test
	public void registro() {
		Optional<User> optUser = usersRepo.findByName("lucia");
		if (optUser.isPresent()) {
			usersRepo.deleteById(optUser.get().getId());
		}
		
		chromeDriver.get("https://localhost:7500/");
		
		/* Para aceptar el Cerficado de conexión no segura y acceder a localhost */
		chromeDriver.findElement(By.id("details-button")).click();
		chromeDriver.findElement(By.id("proceed-link")).click();
		
		WebElement link = chromeDriver.findElement(By.linkText("Crear cuenta"));
		link.click();
		
		WebElement cajaNombre = chromeDriver.findElement(By.xpath("/html/body/div/oj-module/div[1]/div[2]/div/div/div/div[2]/input[1]"));
		WebElement cajaEmail = chromeDriver.findElement(By.xpath("/html/body/div/oj-module/div[1]/div[2]/div/div/div/div[2]/input[2]"));
		WebElement cajaPwd1 = chromeDriver.findElement(By.xpath("/html/body/div/oj-module/div[1]/div[2]/div/div/div/div[2]/input[3]"));
		WebElement cajaPwd2 = chromeDriver.findElement(By.xpath("/html/body/div/oj-module/div[1]/div[2]/div/div/div/div[2]/input[4]"));
		WebElement boton = chromeDriver.findElement(By.xpath("/html/body/div/oj-module/div[1]/div[2]/div/div/div/div[1]/button"));
		
		cajaNombre.sendKeys("lucia");
		cajaEmail.sendKeys("lucia@lucia.com");
		cajaPwd1.sendKeys("lucia123");
		cajaPwd2.sendKeys("lucia123");
		boton.click();
		
		try { Thread.sleep(500); } catch (InterruptedException e ) { }
		
		assertThat(chromeDriver.switchTo().alert().getText(), is("Registrado correctamente"));
		//assertThat(chromeDriver.findElement(By.cssSelector(".oj-hybrid-padding > h1")).getText(), is("Login"));
	}
}
