package edu.uclm.esi.videochat;

// Generated by Selenium IDE
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import org.junit.Test;
import org.junit.After;
import org.junit.Before;
import org.junit.runner.RunWith;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.chrome.ChromeOptions;
import org.openqa.selenium.WebElement;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import edu.uclm.esi.videochat.model.User;
import edu.uclm.esi.videochat.springdao.UserRepository;
import org.openqa.selenium.Alert;
import org.openqa.selenium.JavascriptExecutor;
import java.util.*;
import java.util.concurrent.TimeUnit;


@RunWith(SpringJUnit4ClassRunner.class)
@SpringBootTest
public class TestSeleniumChrome {
	private WebDriver chromeDriver1, chromeDriver2, chromeDriver3;

	JavascriptExecutor js;

	@Autowired
	UserRepository usersRepo;

	@Before
	/* Comun a todos */
	public void setUp() {
		/* Indicamos el path de los drivers */
		System.setProperty("webdriver.chrome.driver", "C:/Users/raulvj/Downloads/chromedriver.exe");
		
		/* Creamos una fake-cam en Chrome */
		ChromeOptions options = new ChromeOptions();
		options.addArguments("--use-fake-ui-for-media-stream");
		options.addArguments("--use-fake-device-for-media-stream");
		
		/* Autorizamos la cámara y el micro en el navegador */
		ChromeOptions options2 = new ChromeOptions();
		HashMap<String, Object> prefs = new HashMap<String, Object>();
		prefs.put("profile.default_content_setting_values.media_stream_mic", 1);
		prefs.put("profile.default_content_setting_values.media_stream_camera", 1);
		options2.setExperimentalOption("prefs", prefs);
		
		/* Creamosm las instancias de los servidores. En este caso, Google Chrome */
		chromeDriver1 = new ChromeDriver(options2);
		chromeDriver2 = new ChromeDriver(options);
		chromeDriver3 = new ChromeDriver(options);
	
		chromeDriver1.manage().timeouts().implicitlyWait(5, TimeUnit.SECONDS);
		chromeDriver2.manage().timeouts().implicitlyWait(5, TimeUnit.SECONDS);
		chromeDriver3.manage().timeouts().implicitlyWait(5, TimeUnit.SECONDS);

		js = (JavascriptExecutor) chromeDriver1;
		js = (JavascriptExecutor) chromeDriver2;
		js = (JavascriptExecutor) chromeDriver3;
		new HashMap<String, Object>();
	}

	@After
	/* Comun a cada caso de prueba */
	public void tearDown() {
		chromeDriver1.quit();
		chromeDriver2.quit();
		chromeDriver3.quit();
	}

	@Test
	public void selenium() {
		/* Buscamos los usuarios en la BD */
		Optional<User> optUser1 = usersRepo.findByName("pepe"); 
		Optional<User> optUser2 = usersRepo.findByName("ana"); 
		Optional<User> optUser3 = usersRepo.findByName("lucas");
		
		/* Borramos los usuarios si es que existen en la BD */
		if (optUser1.isPresent()) { usersRepo.deleteById(optUser1.get().getId()); }
		if (optUser2.isPresent()) { usersRepo.deleteById(optUser2.get().getId()); }
		if (optUser3.isPresent()) { usersRepo.deleteById(optUser3.get().getId()); }

		/* Caso de prueba: se registran 3 usuarios: Pepe, Ana y Lucas */
		register(chromeDriver1, "pepe", "pepe@gmail.com", "pepe123"); 
		register(chromeDriver2, "ana", "ana@gmail.com", "ana123");
		register(chromeDriver3, "lucas", "lucas@gmail.com", "lucas123");
		
		try { Thread.sleep(2000); } catch (InterruptedException e ) { }

		/* Caso de prueba: hacer login con Pepe, Ana y Lucas */
		login(chromeDriver1, "pepe", "pepe123");
		login(chromeDriver2, "ana", "ana123");
		login(chromeDriver3, "lucas", "lucas123");
		
		/* Caso de prueba: Pepe solicita videollamada con Ana, que la rechaza */
		rechazarLlamada(chromeDriver1, chromeDriver2);

		try { Thread.sleep(3000); } catch (InterruptedException e ) { }
		
		/* Caso de prueba: Ana solicita videollamda con Lucas, que la acepta */
		aceptarLlamada(chromeDriver2, chromeDriver3);
		
	}

	private void register(WebDriver driver, String nombre, String email, String pwd) {
		driver.get("https://localhost:7500/");
		
		try { Thread.sleep(2000); } catch (InterruptedException e ) { }
		
		/* Para aceptar el Cerficado de conexión no segura y acceder a localhost */
		if (driver instanceof ChromeDriver) {
			driver.findElement(By.id("details-button")).click();
			driver.findElement(By.id("proceed-link")).click();
		}

		try { Thread.sleep(500); } catch (InterruptedException e) { }
		
		driver.findElement(By.linkText("Crear cuenta")).click();
		
		try { Thread.sleep(500); } catch (InterruptedException e) { }
		
		/* Rellenamos el formulario para registrarnos */
		driver.findElement(By.xpath("/html/body/div/oj-module/div[1]/form/input[1]")).click();
		driver.findElement(By.xpath("/html/body/div/oj-module/div[1]/form/input[1]")).sendKeys(nombre);
		driver.findElement(By.xpath("/html/body/div/oj-module/div[1]/form/input[2]")).click();
		driver.findElement(By.xpath("/html/body/div/oj-module/div[1]/form/input[2]")).sendKeys(email);
		driver.findElement(By.xpath("/html/body/div/oj-module/div[1]/form/input[3]")).click();
		driver.findElement(By.xpath("/html/body/div/oj-module/div[1]/form/input[3]")).sendKeys(pwd);
		driver.findElement(By.xpath("/html/body/div/oj-module/div[1]/form/input[4]")).click();
		driver.findElement(By.xpath("/html/body/div/oj-module/div[1]/form/input[4]")).sendKeys(pwd);
		driver.findElement(By.id("btnCrearCuenta")).click();

		try { Thread.sleep(500); } catch (InterruptedException e) { }
		
		/* Comprobamos que el registro se ha realizado correctamente */
		assertThat(driver.switchTo().alert().getText(), is("Registrado correctamente"));
		
		try { Thread.sleep(1000); } catch (InterruptedException e) { }
		
		driver.switchTo().alert().accept();
		
	}

	private void login(WebDriver driver, String nombre, String pwd) {
		driver.get("https://localhost:7500/");
		
		try { Thread.sleep(500); } catch (InterruptedException e) { }
		
		/* Introducimos las credenciales de acceso */
		driver.findElement(By.xpath("/html/body/div/oj-module/div[1]/form/input[1]")).click();
		driver.findElement(By.xpath("/html/body/div/oj-module/div[1]/form/input[1]")).sendKeys(nombre);
		driver.findElement(By.xpath("/html/body/div/oj-module/div[1]/form/input[2]")).click();
		driver.findElement(By.xpath("/html/body/div/oj-module/div[1]/form/input[2]")).sendKeys(pwd);
		
		driver.findElement(By.xpath("/html/body/div/oj-module/div[1]/form/button")).click();
		
		try { Thread.sleep(500); } catch (InterruptedException e) { }
		
		/* Comprobamos que el login se ha realizado correctamente */
		assertThat(driver.findElement(By.cssSelector(".oj-hybrid-applayout-header-title")).getText(), is("Chat"));

	}

	private void rechazarLlamada(WebDriver driver, WebDriver chromeDriver) {
		WebElement elemento = null;
		int i;
		
		/* Buscamos en la lista de usuarios el elemento deseado */
		for (i = 1; i <= 3; i++) {
			elemento = driver.findElement(By.xpath("/html/body/div/oj-module/div[1]/div[2]/div/div/div[3]/div[1]/div[" + i + "]"));
			if (elemento.getText().contains("ana")) {
				break;
			}
		}
		
		/* Hacemos clic en el botón Hacer llamada correspondiente al usuario */
		WebElement boton = elemento.findElement(By.xpath("/html/body/div/oj-module/div[1]/div[2]/div/div/div[3]/div[1]/div[" + i + "]/button"));
		boton.click();
		
		try { Thread.sleep(3000); } catch (InterruptedException e) { }
		
		/* Ana rechaza la llamada */
		Alert confirmationAlert = chromeDriver.switchTo().alert();
		String alertText = confirmationAlert.getText();
		System.out.println("Alert text is: " + alertText);
		confirmationAlert.dismiss();

		try { Thread.sleep(500); } catch (InterruptedException e) { }
		
		/* Confirmamos que la llamada ha sido rechazada */
		driver.switchTo().alert().accept();
		String texto = driver.findElement(By.xpath("/html/body/div/oj-module/div[1]/div[2]/div/div/div[3]/div[2]")).getText();
		assertThat(texto.contains("La llamada fue rechazada"), is(true));

	}
	
	private void aceptarLlamada(WebDriver chromeDriver, WebDriver driver) {
		WebElement elemento = null;
		int i;
		
		/* Buscamos en la lista de usuarios el elemento deseado */
		for (i = 1; i <= 3; i++) {
			elemento = chromeDriver.findElement(By.xpath("/html/body/div/oj-module/div[1]/div[2]/div/div/div[3]/div[1]/div[" + i + "]"));
			if (elemento.getText().contains("lucas")) {
				break;
			}
		}
		
		/* Hacemos clic en el botón Hacer llamada correspondiente al usuario */
		WebElement boton = elemento.findElement(By.xpath("/html/body/div/oj-module/div[1]/div[2]/div/div/div[3]/div[1]/div[" + i + "]/button"));
		boton.click();
		
		try { Thread.sleep(4000); } catch (InterruptedException e) { }
		
		/* Lucas acepta la llamada */
		Alert confirmationAlert = driver.switchTo().alert();
		String alertText = confirmationAlert.getText();
		System.out.println("Alert text is: " + alertText);
		confirmationAlert.accept();

		try { Thread.sleep(3000); } catch (InterruptedException e) { }
		
		/* Confirmamos que la llamada ha sido aceptada */
		String texto = chromeDriver.findElement(By.xpath("/html/body/div/oj-module/div[1]/div[2]/div/div/div[3]/div[2]")).getText();
		assertThat(texto.contains("La llamada fue aceptada"), is(true));

	}

}
